// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtvLZF8fK875gsYQipgMSycxZg5wKUxlE',
    appId: '1:512224442218:web:44958bbbd2059f89b0d713',
    messagingSenderId: '512224442218',
    projectId: 'crud-users-e9641',
    authDomain: 'crud-users-e9641.firebaseapp.com',
    storageBucket: 'crud-users-e9641.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPLhtki2OEmVoFaJHrGeRVyN9YEEZrWmg',
    appId: '1:512224442218:android:040936d61a10a2b3b0d713',
    messagingSenderId: '512224442218',
    projectId: 'crud-users-e9641',
    storageBucket: 'crud-users-e9641.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAd3Yg2mSAzbwkC5MoNMYXO0gQrqaiFeA4',
    appId: '1:512224442218:ios:61be10e1ffe563bfb0d713',
    messagingSenderId: '512224442218',
    projectId: 'crud-users-e9641',
    storageBucket: 'crud-users-e9641.appspot.com',
    iosBundleId: 'com.example.crudapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAd3Yg2mSAzbwkC5MoNMYXO0gQrqaiFeA4',
    appId: '1:512224442218:ios:5bcd74694fd885b4b0d713',
    messagingSenderId: '512224442218',
    projectId: 'crud-users-e9641',
    storageBucket: 'crud-users-e9641.appspot.com',
    iosBundleId: 'com.example.crudapp.RunnerTests',
  );
}
